name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # - name: Run Checkstyle
    #   run: gradle check --stacktrace

    # - name: Upload Checkstyle Report
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: checkstyle-report
    #     path: Spotify-Wrapped/app/build/reports/checkstyle/checkstyle.html

    # - name: gradle build
    #   run: ./gradlew build

    - name: make new directory
      run: mkdir downloads

    - name: go into new directory
      run: |
        cd downloads
        echo "$GITHUB_WORKSPACE" > testing.txt
        cd ..

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: assets-for-downloads
        path: downloads 

    - name: upload artifact 2
    - run: mkdir -p $GITHUB_WORKSPACE
    - run: echo hello > $GITHUB_WORKSPACE/build.gradle
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: $GITHUB_WORKSPACE/build.gradle

        
      
