name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run Checkstyle
      run: gradle check --stacktrace

    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-report
        path: Spotify-Wrapped/app/build/reports/checkstyle/checkstyle.html

    # - name: Run Gradle build
    #   run: ./gradlew build
